# -*- coding: utf-8 -*-
"""W12-A105260051-官廷樺.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b0i2NmvxRA8SipKCC0emfF1-ZBIVLHQX

#隨堂練習:

印出介於 x 到 y 之間的奇數（包含 x 與 y 假如它們是奇數）
"""

x = int(input("請輸入起始的正整數:"))
y = int(input("請輸入終止的正整數:"))
odds = []
for i in range(x, y+1):
    mod = i % 2
    if mod == 1:
        odds.append(i)
print(odds)

"""#隨堂練習:

承接上題，介於 x 到 y 之間的奇數有幾個（包含 x 與 y 假如它們是奇數）
"""

print(len(odds)) # 記數
print(sum(odds)) # 加總

"""#隨堂練習:

將復仇者聯盟系列電影評等⼤於 8 分的挑選出來
"""

avengers_ratings = [8.1, 7.3, 8.5, 8.8]
recommendations = [i for i in avengers_ratings if i >= 8]
print(recommendations)

weekdays = ['Monday','Tuesday', 'Wednesday', 'Thursday', 'Friday']
for i, wd in enumerate(weekdays):
    print("{}:星期{}".format(wd, i+1))

"""#隨堂練習:

標記復仇者聯盟的上映順序

第 1 部上映的復仇者聯盟是：The Avengers

第 2 部上映的復仇者聯盟是：Avengers: Age of Ultron

第 3 部上映的復仇者聯盟是：Avengers: Infinity War

第 4 部上映的復仇者聯盟是：Avengers: Endgame
"""

avengers = ["The Avengers", "Avengers: Age of Ultron", "Avengers: Infinity War", "Avengers: Endgame"]
for idx, movie in enumerate(avengers):
    print("第{}部上映的復仇者聯盟電影:{}".format(idx+1, movie))

years = [2012, 2015, 2018, 2019]
for year, movue in zip(years, avengers):
    print("{}上映的年份是{}".format(movie, year))