# -*- coding: utf-8 -*-
"""W7_A105260051_官廷樺.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EpPj-VKcHE11-rTY-EIEillZSQ83zpP5

隨堂練習： 月薪超過 4 萬或存款超過 50 萬就發信用卡
"""

monthly_income = input("請輸入月薪")
saving_account = input("請輸入存款")
monthly_income = int(monthly_income)
saving_account = int(saving_account)
print(type(monthly_income))
print(type(saving_account))
ans = ""
# 條件判斷()begin
if monthly_income > 40000 or saving_account > 500000:
    ans = "發信用卡"
# 條件判斷(end)
print(ans)

"""隨堂練習： 判斷奇數偶數

請輸入一個正整數：5566

5566 是偶數

請輸入一個正整數：87

87 是奇數
"""

user_int = input("請輸入一個正整數")
user_int = int(user_int)
if user_int % 2 == 0:
    ans = "偶數"
else:
    ans = "奇數"
print(ans)

"""隨堂練習： 依身分證字號尾數決定星期幾可以購買口罩

奇數：星期一三五日領

偶數：星期二四六日領
"""

id_last_digit = input("請輸入您身分證字號的尾數")
id_last_digit = int(id_last_dight)
if id_last_digit % 2 == 0:
    ans = "星期二四六領"
else:
    ans = "星期一三五日領"
print(ans)

"""隨堂練習： 判斷 BMI 的類別標籤

請輸入身高（公分）：200

請輸入體重（公斤）：80

身高 200.0 公分、體重 80.0 公斤，是 Normal weight

請輸入身高（公分）：170

請輸入體重（公斤）：100

身高 170.0 公分、體重 100.0 公斤，是 Obese
"""

input_height = float(input("請輸入身高（公分）："))
input_weight = float(input("請輸入體重（公斤）："))
bmi = input_weight / (input_height*0.01)**2
if bmi > 30:
    label = "Obese"
elif bmi > 25:
    label = "Overweight"
elif bmi > 18.5:
    label = "Normal weight"
else:
    label = "Underweight"
print(label)

input_height = float(input("請輸入身高（公分）："))
input_weight = float(input("請輸入體重（公斤）："))
bmi = input_weight / (input_height*0.01)**2
if bmi > 30:
    label = "Obese"
if bmi > 25:
    label = "Overweight"
if bmi > 18.5:
    label = "Normal weight"
if bmi <= 18.5:
    label = "Underweight"
print(label)