# -*- coding: utf-8 -*-
"""W9-A105260051-官廷樺.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_AU0HXlFwpZpj8Am-EGvyWcEcrWO4cL-

隨堂練習：
印出介於 x 到 y 之間的奇數
（包含 x 與 y 假如它們是奇數）
"""

x = int(input("請輸入起始的整數:"))
y = int(input("請輸入終止的整數:"))
i = x # start
while i <= y: # stop
    # task
    if i % 2 == 1:
        print(i)
    i += 1 # step

"""隨堂練習：承接上題，介於 x 到 y 之間的奇數有幾個

（包含 x 與 y 假如它們是奇數）
"""

x = int(input("請輸入起始的整數:"))
y = int(input("請輸入終止的整數:"))
odd_counter = 0 # 歸零
i = x # start
while i <= y: # stop
    # task
    if i % 2 == 1:
        #odd_counter = odd_counter + 1 # = NOT ==
        odd_counter += 1 #計數累計
    #print(odd_counter)
    i += 1 # step
print("=====")
print(odd_counter)

"""隨堂練習：承接上題，介於 x 到 y 之間的奇數加總為何

（包含 x 與 y 假如它們是奇數）
"""

x = int(input("請輸入起始的整數:"))
y = int(input("請輸入終止的整數:"))
odd_summation = 0 # 歸零
i = x # start
while i <= y: # stop
    # task
    if i % 2 == 1:
        odd_summation = odd_summation + i # 數值累計
    i += 1 # stop
    print("=====")
print(odd_summation)

x = int(input("請輸入一個正整數"))
i = 1 #start
divisor_counter = 0 #歸零
while i <= x:  # stop
    if x % i == 0:
        divisor_counter += 1  
        print("{} 可以被{}整除".format(x, i))
        print("因數個數目前有{}個".format(divisor_counter))
        print("=====")
    i += 1 # step

"""判斷質數

在⼤於 1 的正整數中，除了 1 和該數⾃⾝外，無法被其他正整數整除的數字。
"""

x = int(input("請輸入一個正整數"))
i = 1 #start
divisor_counter = 0 #歸零
while i <= x:  # stop
    if x % i == 0:
        divisor_counter += 1  
        print("{} 可以被{}整除".format(x, i))
        print("因數個數目前有{}個".format(divisor_counter))
        print("=====")
    i += 1 # step
print("### Answer ###")
print("{}有{}個因數!".format(x, divisor_counter))
if divisor_counter == 2:
    print("{}是質數".format(x))
else:
    print("{}不是質數.format(x)")

"""作業：Fizz-Buzz with while

從 1 印到 100

如果是 3 的倍數印出 "Fizz"

如果是 5 的倍數印出 "Buzz"

如果是 15 的倍數印出 "Fizz Buzz"

其他情況印出該正整數即可
"""

i = 1
while i <= 100:
    if i % 15 == 0:
        print("Fizz Buzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)
    i += 1