# -*- coding: utf-8 -*-
"""W3-A105260051-官廷樺

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZUmYvcNQtNQC5-eW43Y8NXmuhnaLfq5_

隨堂練習： 將電影 https://www.imdb.com/title/tt4154796
(https://www.imdb.com/title/tt4154796) 頁面中的三個資訊
儲存為物件並且印出來
片長（以分鐘為單位）
評分
片名
"""

movie_title = "Avengers: Endgame"
movie_length = 181
movie_rating = 8.4

print(movie_title)
print(movie_length)
print(movie_rating)

"""隨堂練習： 使用 type() 函數將這三個物件的類別印出來"""

print(type(movie_title))
print(type(movie_length))
print(type(movie_rating))