# -*- coding: utf-8 -*-
"""W10-A105260051-官廷樺.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1beYAxjvlIRS8Cnb8T4sosmZt_mRbnVNk

參考 cast 與

https://www.imdb.com/title/tt4154796(https://www.imdb.com/title/tt4154796) 

將飾演奇異博⼠（Doctor Strange）的演員⽤ indexing ⽅式選出來
"""

cast = ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson', 'Jeremy Renner', 'Don Cheadle', 'Paul Rudd', 'Benedict Cumberbatch', 'Chadwick Boseman', 'Brie Larson', 'Tom Holland', 'Karen Gillan', 'Zoe Saldana', 'Evangeline Lilly']
print(cast[8])

"""參考 cast 與

https://www.imdb.com/title/tt4154796(https://www.imdb.com/title/tt4154796) 

 將第⼀集復仇者聯盟的六位英雄選出來
"""

print(len(cast))
print(cast[:6])

import pandas as pd

time_series_df = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
cumulative_confirmed = list(time_series_df[time_series_df['Country/Region'] == 'Taiwan*'].values.ravel()[4:].astype(int))
cumulative_confirmed_lag = list(time_series_df[time_series_df['Country/Region'] == 'Taiwan*'].values.ravel()[4:].astype(int))
print(cumulative_confirmed)
print(cumulative_confirmed_lag)

print(len(cumulative_confirmed))
print(cumulative_confirmed[-1])

cumulative_confirmed_lag.insert(0, 0)
print(len(cumulative_confirmed_lag))
print(cumulative_confirmed_lag[0])

cumulative_confirmed_lag.pop()
print(len(cumulative_confirmed_lag))
print(cumulative_confirmed_lag[-1])

print(cumulative_confirmed)
print(cumulative_confirmed_lag)

daily_increase = []

#daily_increase = ?
day0_increase = cumulative_confirmed[0] - cumulative_confirmed_lag[0]
print(day0_increase)
daily_increase.append(day0_increase)

day1_increase = cumulative_confirmed[1] - cumulative_confirmed_lag[1]
print(day1_increase)
daily_increase.append(day1_increase)

day2_increase = cumulative_confirmed[2] - cumulative_confirmed_lag[2]
print(day2_increase)
daily_increase.append(day2_increase)

daily_increase

day106_increase = cumulative_confirmed[106] - cumulative_confirmed_lag[106]
print(day106_increase)

daily_increase = []
i = 0
while i < 107:
    dayn_increase = cumulative_confirmed[i] - cumulative_confirmed_lag[i]
    print("Day {}: 每日新增確診人數 {}".format(i, dayn_increase))
    daily_increase.append(dayn_increase)
    i += 1

