# -*- coding: utf-8 -*-
"""W11-A105260051-官廷樺.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wSPDQ4R9d04VN15wjV4ZXFYOfUBrNWRe
"""

the_avengers = {
    "Iron Man": "Tony Stark",
    "Captain America": "Steve Rogers",
    "Hulk": "Bruce Banner",
    "Thor": "Thor",
    "Black Widow": "Natasha Romanoff",
    "Hawkeye": "Clint Barton"
}

print(type(the_avengers))

print(the_avengers.keys())

print(the_avengers.values())

print(the_avengers.items())

living_area = input("請輸入您的居住縣市:")
living_cost = None
if living_area == '臺北市':
    living_cost = 17005
    print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))
elif living_area == '新北市':
    living_cost = 15500
    print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))
elif living_area == '桃園市':
    living_cost = 15281
    print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))
elif living_area == '臺中市':
    living_cost = 14596
    print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))
elif living_area == '臺南市':
    living_cost = 12388
    print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))
elif living_area == '高雄市':
    living_cost = 13099
    print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))
elif living_area == '非六都之縣市':
    living_cost = 12388
    print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))
elif living_area == '金門縣連江縣':
    living_cost = 11648
    print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))
else:
    print("請重新輸入居住縣市")

living_cost_dict = {
    '臺北市': 17005,
    '新北市': 15500,
    '桃園市': 15281,
    '臺中市': 14596,
    '臺南市': 12388,
    '高雄市': 13099,
    '非六都之縣市': 12388,
    '金門縣連江縣': 11648
}

living_area = input("請輸入您的居住縣市:")
living_cost = living_cost_dict[living_area]
print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))

primes = {2, 3, 5, 7, 11, 13}
print(primes)
print(type(primes))

primes_list = [2, 3, 3, 3, 5, 5]
print(primes_list)

set(primes_list)

primes = {2, 3, 5, 7, 11, 13, 13, 13, 11, 11, 11, 11, 2, 2, 2}
print(primes)

primes = {2, 3, 5, 7, 11, 13}
odds = {1, 3, 5, 7, 9, 11, 13}
print(type(primes))
print(type(odds))

# 交集
primes & odds

# intersection
primes | odds

# .union 
primes.union(odds)

# 差異
print(primes - odds)
print(odds - primes)

# .difference
print(primes.difference(odds))
print(odds.difference(primes))

(primes - odds) | (odds - primes)

# 對稱差異
primes ^ odds

# .symmetric_difference
print(primes.symmetric_difference(odds))

import requests

today_json = requests.get("https://data.nba.net/10s/prod/v1/today.json").json()
print(type(today_json))

today_json.keys()

print(type(today_json['links']))

primes_list = [2, 3, 5, 7, 11]
I = iter(primes_list)
next(I)

primes_tuple = (2, 3, 5, 7, 11)
I = iter(primes_tuple)
next(I)

I = iter(living_cost_dict.keys())
next(I)

I = iter(living_cost_dict.values())
next(I)

I = iter(living_cost_dict.items())
next(I)

may4th = "Luke, use the Force!"

help(range)

for i in range(1, 101):
    print(i)

